### ISSUE TITLE
Typo in SeqLib configuration details/counts file

### ISSUE THREAD

**Issue by hansenjeff2** [FowlerLab/Enrich2#11]
The note under "Counts File" of the documentation (https://enrich2.readthedocs.io/en/latest/seqlib_config.html) specifies that these files require "counts" as the heading of the second column. This contradicts your error message in your counts_from_file_tsv function in seqlib.py script that requires "count" as the heading of the second column.

**Comment by afrubin** [comment]
Thanks! The documentation has been fixed in the dev branch and will appear in the next update.
