### ISSUE TITLE
Failed to open config file after ctrl-C shutdown

### ISSUE THREAD

**Issue by flamholz** [FowlerLab/Enrich2#13]
I accidentally set "use aligner" so I ctrl-C'd enrich_gui and now it won't open the saved config file. 
The error is "Failed to process config file: Non-unique selection names [csosCA selections]" but the phrase "csosCA selections" appears only one time in the config file. Very confusing error.

**Comment by flamholz** [comment]
OK I figured out what the error means: 
It means that my selection names are not unique - I edited them in the JSON to be unique and now it will load. In retrospect it seems clear, but it would be much clearer if (1) the configurator didn't allow me to save invalid configurations and (2) if you told me which selection names were not unique in the error. 

As written it's not clear what the error means on first blush.

**Comment by afrubin** [comment]
Thank you for pointing out this lack of clarity.  We'll add this to the list of things to improve for the next version.
