### ISSUE TITLE
Failed to use wild type log ratio method

### ISSUE THREAD

**Issue by diabatem** [FowlerLab/Enrich2#21]
I am attempting to do an Enrich2 analysis, and I keep receiving this error message "Failed to use wild type log ratio method, wild type sequence not present". I checked the files and they are not identical, and I do not understand why the error is raised. 
<img width="869" alt="screen shot 2018-11-02 at 2 05 35 pm" src="https://user-images.githubusercontent.com/44099117/47932577-6bd82700-dea8-11e8-9ed3-f1e4d88ba678.png">
[C-termExperiment.zip](https://github.com/FowlerLab/Enrich2/files/2543619/C-termExperiment.zip)

**Comment by afrubin** [comment]
Do you have a wild type sequence specified in the configuration file?

**Comment by diabatem** [comment]
Yes, it is specified.
