### ISSUE TITLE
Sequence-function map table

### ISSUE THREAD

**Issue by dtdoering** [FowlerLab/Enrich2#22]
Similar to #17, it would be nice to have access to the numbers behind the sequence-function maps. Whether this is by codon or by amino acid, having the data would make plotting Enrich2 values onto molecular structures in PyMOL much easier. I've searched through the documentation and the HDF5 files and can't seem to find anything similar, but maybe I missed something.

I know lots of DMS papers have figures like this one below (Fig. 2 from [Melamed *et al.*, 2013 *RNA*](https://rnajournal.cshlp.org/content/early/2013/09/24/rna.040709.113.full.pdf)): 

![screen shot 2018-11-15 at 1 57 21 pm](https://user-images.githubusercontent.com/8560137/48578122-70f09980-e8de-11e8-8bd4-ce2cfd1fd977.png)

Having access to these data would make projecting them onto structures much easier. Anyways, thanks for the great software! Going to be using it a lot over the next several months.

Cheers!

**Comment by afrubin** [comment]
You can extract this information by looking for single amino acid variants in the score tables, but I agree that having something that's easier for plotting packages to consume without needing extra filtering would be helpful. I'll add this to the list of features to implement before the next release.
