### ISSUE TITLE
problem with installing Enrich on Centos6.6

### ISSUE THREAD

**Issue by pcieplak** [FowlerLab/Enrich2#23]
I am having problem with installing Enrich2 on my linux box.
The last error message when doing python setup.py install   (after ...setup.py build) is: 
TypeError: __init__() takes exactly 2 arguments (4 given)

Can anybody help with this issue. I would appreciate.

Best regards.

The entire log from this install is as follows:

sudo python setup.py install
running install
running bdist_egg
running egg_info
/usr/lib/python2.6/site-packages/setuptools/command/egg_info.py:171: DeprecationWarning: Parameters to load are deprecated.  Call .resolve and .require separately.
  writer = ep.load(installer=installer)
writing requirements to Enrich2.egg-info/requires.txt
writing Enrich2.egg-info/PKG-INFO
writing top-level names to Enrich2.egg-info/top_level.txt
writing dependency_links to Enrich2.egg-info/dependency_links.txt
writing entry points to Enrich2.egg-info/entry_points.txt
writing requirements to Enrich2.egg-info/requires.txt
writing Enrich2.egg-info/PKG-INFO
writing top-level names to Enrich2.egg-info/top_level.txt
writing dependency_links to Enrich2.egg-info/dependency_links.txt
writing entry points to Enrich2.egg-info/entry_points.txt
reading manifest file 'Enrich2.egg-info/SOURCES.txt'
reading manifest template 'MANIFEST.in'
no previously-included directories found matching 'docs/_build'
writing manifest file 'Enrich2.egg-info/SOURCES.txt'
installing library code to build/bdist.linux-x86_64/egg
running install_lib
running build_py
creating build/bdist.linux-x86_64/egg
creating build/bdist.linux-x86_64/egg/enrich2
copying build/lib/enrich2/__init__.py -> build/bdist.linux-x86_64/egg/enrich2
copying build/lib/enrich2/aligner.py -> build/bdist.linux-x86_64/egg/enrich2
copying build/lib/enrich2/barcode.py -> build/bdist.linux-x86_64/egg/enrich2
copying build/lib/enrich2/barcodeid.py -> build/bdist.linux-x86_64/egg/enrich2
copying build/lib/enrich2/barcodemap.py -> build/bdist.linux-x86_64/egg/enrich2
copying build/lib/enrich2/barcodevariant.py -> build/bdist.linux-x86_64/egg/enrich2
copying build/lib/enrich2/basic.py -> build/bdist.linux-x86_64/egg/enrich2
copying build/lib/enrich2/condition.py -> build/bdist.linux-x86_64/egg/enrich2
copying build/lib/enrich2/config_check.py -> build/bdist.linux-x86_64/egg/enrich2
copying build/lib/enrich2/constants.py -> build/bdist.linux-x86_64/egg/enrich2
copying build/lib/enrich2/dataframe.py -> build/bdist.linux-x86_64/egg/enrich2
copying build/lib/enrich2/experiment.py -> build/bdist.linux-x86_64/egg/enrich2
copying build/lib/enrich2/fqread.py -> build/bdist.linux-x86_64/egg/enrich2
copying build/lib/enrich2/idonly.py -> build/bdist.linux-x86_64/egg/enrich2
copying build/lib/enrich2/main.py -> build/bdist.linux-x86_64/egg/enrich2
copying build/lib/enrich2/overlap.py -> build/bdist.linux-x86_64/egg/enrich2
copying build/lib/enrich2/plots.py -> build/bdist.linux-x86_64/egg/enrich2
copying build/lib/enrich2/random_effects.py -> build/bdist.linux-x86_64/egg/enrich2
copying build/lib/enrich2/selection.py -> build/bdist.linux-x86_64/egg/enrich2
copying build/lib/enrich2/seqlib.py -> build/bdist.linux-x86_64/egg/enrich2
copying build/lib/enrich2/sfmap.py -> build/bdist.linux-x86_64/egg/enrich2
copying build/lib/enrich2/storemanager.py -> build/bdist.linux-x86_64/egg/enrich2
copying build/lib/enrich2/variant.py -> build/bdist.linux-x86_64/egg/enrich2
copying build/lib/enrich2/wildtype.py -> build/bdist.linux-x86_64/egg/enrich2
copying build/lib/enrich2/ztest.py -> build/bdist.linux-x86_64/egg/enrich2
creating build/bdist.linux-x86_64/egg/enrich2/gui
copying build/lib/enrich2/gui/__init__.py -> build/bdist.linux-x86_64/egg/enrich2/gui
copying build/lib/enrich2/gui/configurator.py -> build/bdist.linux-x86_64/egg/enrich2/gui
copying build/lib/enrich2/gui/create_root_dialog.py -> build/bdist.linux-x86_64/egg/enrich2/gui
copying build/lib/enrich2/gui/create_seqlib_dialog.py -> build/bdist.linux-x86_64/egg/enrich2/gui
copying build/lib/enrich2/gui/delete_dialog.py -> build/bdist.linux-x86_64/egg/enrich2/gui
copying build/lib/enrich2/gui/dialog_elements.py -> build/bdist.linux-x86_64/egg/enrich2/gui
copying build/lib/enrich2/gui/edit_dialog.py -> build/bdist.linux-x86_64/egg/enrich2/gui
copying build/lib/enrich2/gui/runner_window.py -> build/bdist.linux-x86_64/egg/enrich2/gui
copying build/lib/enrich2/gui/seqlib_apply_dialog.py -> build/bdist.linux-x86_64/egg/enrich2/gui
byte-compiling build/bdist.linux-x86_64/egg/enrich2/__init__.py to __init__.pyc
byte-compiling build/bdist.linux-x86_64/egg/enrich2/aligner.py to aligner.pyc
byte-compiling build/bdist.linux-x86_64/egg/enrich2/barcode.py to barcode.pyc
byte-compiling build/bdist.linux-x86_64/egg/enrich2/barcodeid.py to barcodeid.pyc
SyntaxError: ('invalid syntax', ('build/bdist.linux-x86_64/egg/enrich2/barcodeid.py', 113, 52, "            self.save_counts('identifiers', {k:v for k,v in df_dict.iteritems() if v >= self.identifier_min_count}, raw=False)\n"))

byte-compiling build/bdist.linux-x86_64/egg/enrich2/barcodemap.py to barcodemap.pyc
byte-compiling build/bdist.linux-x86_64/egg/enrich2/barcodevariant.py to barcodevariant.pyc
SyntaxError: ('invalid syntax', ('build/bdist.linux-x86_64/egg/enrich2/barcodevariant.py', 115, 49, "            self.save_counts('variants', {k:v for k,v in df_dict.iteritems() if v >= self.variant_min_count}, raw=False)\n"))

byte-compiling build/bdist.linux-x86_64/egg/enrich2/basic.py to basic.pyc
byte-compiling build/bdist.linux-x86_64/egg/enrich2/condition.py to condition.pyc
byte-compiling build/bdist.linux-x86_64/egg/enrich2/config_check.py to config_check.pyc
byte-compiling build/bdist.linux-x86_64/egg/enrich2/constants.py to constants.pyc
byte-compiling build/bdist.linux-x86_64/egg/enrich2/dataframe.py to dataframe.pyc
byte-compiling build/bdist.linux-x86_64/egg/enrich2/experiment.py to experiment.pyc
byte-compiling build/bdist.linux-x86_64/egg/enrich2/fqread.py to fqread.pyc
byte-compiling build/bdist.linux-x86_64/egg/enrich2/idonly.py to idonly.pyc
byte-compiling build/bdist.linux-x86_64/egg/enrich2/main.py to main.pyc
byte-compiling build/bdist.linux-x86_64/egg/enrich2/overlap.py to overlap.pyc
byte-compiling build/bdist.linux-x86_64/egg/enrich2/plots.py to plots.pyc
byte-compiling build/bdist.linux-x86_64/egg/enrich2/random_effects.py to random_effects.pyc
byte-compiling build/bdist.linux-x86_64/egg/enrich2/selection.py to selection.pyc
byte-compiling build/bdist.linux-x86_64/egg/enrich2/seqlib.py to seqlib.pyc
byte-compiling build/bdist.linux-x86_64/egg/enrich2/sfmap.py to sfmap.pyc
byte-compiling build/bdist.linux-x86_64/egg/enrich2/storemanager.py to storemanager.pyc
byte-compiling build/bdist.linux-x86_64/egg/enrich2/variant.py to variant.pyc
byte-compiling build/bdist.linux-x86_64/egg/enrich2/wildtype.py to wildtype.pyc
byte-compiling build/bdist.linux-x86_64/egg/enrich2/ztest.py to ztest.pyc
byte-compiling build/bdist.linux-x86_64/egg/enrich2/gui/__init__.py to __init__.pyc
byte-compiling build/bdist.linux-x86_64/egg/enrich2/gui/configurator.py to configurator.pyc
byte-compiling build/bdist.linux-x86_64/egg/enrich2/gui/create_root_dialog.py to create_root_dialog.pyc
byte-compiling build/bdist.linux-x86_64/egg/enrich2/gui/create_seqlib_dialog.py to create_seqlib_dialog.pyc
byte-compiling build/bdist.linux-x86_64/egg/enrich2/gui/delete_dialog.py to delete_dialog.pyc
byte-compiling build/bdist.linux-x86_64/egg/enrich2/gui/dialog_elements.py to dialog_elements.pyc
byte-compiling build/bdist.linux-x86_64/egg/enrich2/gui/edit_dialog.py to edit_dialog.pyc
byte-compiling build/bdist.linux-x86_64/egg/enrich2/gui/runner_window.py to runner_window.pyc
byte-compiling build/bdist.linux-x86_64/egg/enrich2/gui/seqlib_apply_dialog.py to seqlib_apply_dialog.pyc
creating build/bdist.linux-x86_64/egg/EGG-INFO
copying Enrich2.egg-info/PKG-INFO -> build/bdist.linux-x86_64/egg/EGG-INFO
copying Enrich2.egg-info/SOURCES.txt -> build/bdist.linux-x86_64/egg/EGG-INFO
copying Enrich2.egg-info/dependency_links.txt -> build/bdist.linux-x86_64/egg/EGG-INFO
copying Enrich2.egg-info/entry_points.txt -> build/bdist.linux-x86_64/egg/EGG-INFO
copying Enrich2.egg-info/requires.txt -> build/bdist.linux-x86_64/egg/EGG-INFO
copying Enrich2.egg-info/top_level.txt -> build/bdist.linux-x86_64/egg/EGG-INFO
zip_safe flag not set; analyzing archive contents...
creating 'dist/Enrich2-1.2.0-py2.6.egg' and adding 'build/bdist.linux-x86_64/egg' to it
removing 'build/bdist.linux-x86_64/egg' (and everything under it)
Processing Enrich2-1.2.0-py2.6.egg
removing '/usr/lib/python2.6/site-packages/Enrich2-1.2.0-py2.6.egg' (and everything under it)
creating /usr/lib/python2.6/site-packages/Enrich2-1.2.0-py2.6.egg
Extracting Enrich2-1.2.0-py2.6.egg to /usr/lib/python2.6/site-packages
SyntaxError: ('invalid syntax', ('/usr/lib/python2.6/site-packages/Enrich2-1.2.0-py2.6.egg/enrich2/barcodeid.py', 113, 52, "            self.save_counts('identifiers', {k:v for k,v in df_dict.iteritems() if v >= self.identifier_min_count}, raw=False)\n"))

SyntaxError: ('invalid syntax', ('/usr/lib/python2.6/site-packages/Enrich2-1.2.0-py2.6.egg/enrich2/barcodevariant.py', 115, 49, "            self.save_counts('variants', {k:v for k,v in df_dict.iteritems() if v >= self.variant_min_count}, raw=False)\n"))

Enrich2 1.2.0 is already the active version in easy-install.pth
Installing enrich_cmd script to /usr/bin
Installing enrich_gui script to /usr/bin

Installed /usr/lib/python2.6/site-packages/Enrich2-1.2.0-py2.6.egg
Traceback (most recent call last):
  File "setup.py", line 57, in <module>
    install_requires=requirements,
  File "/usr/lib64/python2.6/distutils/core.py", line 152, in setup
    dist.run_commands()
  File "/usr/lib64/python2.6/distutils/dist.py", line 975, in run_commands
    self.run_command(cmd)
  File "/usr/lib64/python2.6/distutils/dist.py", line 995, in run_command
    cmd_obj.run()
  File "/usr/lib/python2.6/site-packages/setuptools/command/install.py", line 73, in run
    self.do_egg_install()
  File "/usr/lib/python2.6/site-packages/setuptools/command/install.py", line 101, in do_egg_install
    cmd.run()
  File "/usr/lib/python2.6/site-packages/setuptools/command/easy_install.py", line 236, in run
    self.easy_install(spec, not self.no_deps)
  File "/usr/lib/python2.6/site-packages/setuptools/command/easy_install.py", line 452, in easy_install
    return self.install_item(None, spec, tmpdir, deps, True)
  File "/usr/lib/python2.6/site-packages/setuptools/command/easy_install.py", line 504, in install_item
    self.process_distribution(spec, dist, deps)
  File "/usr/lib/python2.6/site-packages/setuptools/command/easy_install.py", line 540, in process_distribution
    distreq.project_name, distreq.specs, requirement.extras
TypeError: __init__() takes exactly 2 arguments (4 given)

**Comment by afrubin** [comment]
Installing Enrich2 and its dependencies from source can be quite challenging and system-specific, and as such it is not something I'm able to support directly.

I recommend installing Enrich2's dependencies using Anaconda. The [documentation](https://enrich2.readthedocs.io/en/latest/installation.html#installation-and-example-dataset) includes some more details and a link to a conda environment file that should get you up and running.

**Comment by pcieplak** [comment]
Ok. But can anything be deducted from the log file which I sent you? What went wrong with installing enrich2?

Thanks,
Piotr

**Comment by afrubin** [comment]
My best guess is that Enrich2 uses language features that are supported in Python 2.7 but not in Python 2.6. This may account for the `SyntaxError` exceptions you're seeing.

I haven't tested or developed Enrich2 with Python 2.6 in mind, since [it was already getting old when I started work on the project](https://www.python.org/dev/peps/pep-0361/#release-lifespan).

Please try it with Python 2.7.15 (ideally through Anaconda) and see if that solves the problems.
