### ISSUE TITLE
Failed to process config file

### ISSUE THREAD

**Issue by diabatem** [FowlerLab/Enrich2#26]
Hello, 
I am attempting to run enrich2 on a json, that previously (a week ago) worked for me. The error message I get states: Failed to process config file: Could not open the barcode map file. I have verified that the file paths are correct and none of the files are corrupt.  Below, I have attached the config file that is not working for me. 
[Pool5_shifted.zip](https://github.com/FowlerLab/Enrich2/files/3917583/Pool5_shifted.zip)
<img width="422" alt="Screen Shot 2019-12-03 at 11 20 27 AM" src="https://user-images.githubusercontent.com/44099117/70068951-f107a100-15be-11ea-9532-9076e6b416b2.png">

**Comment by afrubin** [comment]
It looks like your barcode map file is missing the leading `/` so the program is trying to open it as a relative path instead of an absolute path.

I'm not sure how it was removed but try adding it back and let me know if that works.

**Comment by diabatem** [comment]
Yes, that was the source of the problem.
