### ISSUE TITLE
KeyError: 'BasicSeqLib'

### ISSUE THREAD

**Issue by b-robison** [FowlerLab/Enrich2#34]
Hi Alan,

Thanks for your recent 1.3.0 update. 

After upgrading from 1.2.x to 1.3.0, I am able to run the example BRCA1 analysis, but my own simple selection analysis fails at the selection.py configure step (line 163, see err.txt). My config file looks fine on JSONLint (see attached, anonymized file). Reads are one end of paired-end reads. 

[test_sel_config.txt](https://github.com/FowlerLab/Enrich2/files/4441442/test_sel_config.txt)

[err.txt](https://github.com/FowlerLab/Enrich2/files/4441444/err.txt)

Any help would be appreciated.
Brett

**Comment by afrubin** [comment]
Thanks for this report!

This is a real bug I created during the 1.3.0 code cleanup and I'll get a version 1.3.1 out later today that fixes it.
