### ISSUE TITLE
Failed to count variants [E3]

### ISSUE THREAD

**Issue by VikasDT** [FowlerLab/Enrich2#37]
I am getting the following error while trying to run the analysis "Failed to count variants [E3]"

**Comment by afrubin** [comment]
This can happen for a lot of reasons. Usually it is because your filtering or trimming options are set such that no reads pass (and therefore no variants are counted). I recommend double-checking these parts of your configuration file.

**Comment by VikasDT** [comment]
Thanks for writing back, I checked all these parameters. I am using the
exact same parameters as mentioned in the document.
Is there anything else I can try?

**Comment by VikasDT** [comment]
I could work my way around this finally. Thanks

**Comment by Behvar** [comment]
> I could work my way around this finally. Thanks

ViKasDT,
Would you please what was the problem with this error? (if you can remember it by any chance)
