### ISSUE TITLE
Errors running Enrich2 from GUI and CMD

### ISSUE THREAD

**Issue by kristinalweber** [FowlerLab/Enrich2#4]
Hey! I am trying to run Enrich2 and encountering some problems. We installed to our HPC and were able to run the example dataset. However, when we tried to run a small test set of our data, we got a bunch of errors. From the GUI, the process would not run at all - it said that the wildtype sequence was not protein coding, but we've verified that the sequence is correct. From CMD, it would run but would quit with an "operands could not be broadcast together with shapes" error. Further, there are a lot of warning about dataset size; however, this is only a subset of the true NGS dataset (~275K reads/sample vs. 20M reads in full dataset). Could you make any suggestions about how we might address these issues (json, log, and error messages attached)? Thanks! Kristina

json file
[Lisa_Ag_exc_json.txt](https://github.com/FowlerLab/Enrich2/files/634623/Lisa_Ag_exc_json.txt)

log file
[log.txt](https://github.com/FowlerLab/Enrich2/files/634626/log.txt)

printed error messages
[error_messages.txt](https://github.com/FowlerLab/Enrich2/files/634628/error_messages.txt)

**Comment by afrubin** [comment]
Hi, happy to help sort this out!

In the log it shows that all variants are being called using the aligner, which indicates that your read length doesn't match the wild type sequence length. This is related to the PyTables memory warning, which I usually see when the number of mutations per variant (and therefore length of variant string) is very high.

Please have a look at the reads and make sure they don't need trimming to match the wild type sequence and let me know how it goes. The reads and wild type should be the same length, start at the same place, and be in-frame.

Thanks!

**Comment by kristinalweber** [comment]
?Thanks for getting back to me so quickly. What about when the reads are shorter than the wild type sequence length? Our NGS reads are much short than the target sequence, but when aligned, should cover it deeply. Can Enrich2 align the short reads against the target and detect mutations relative to it?


Thanks

Kristina


Kristina L. Weber, PhD | Senior scientist
Zoetis | Genetics R&D | 333 Portage St, KZO300-387F, Kalamazoo, MI 49007
Office: 269.359.9591 (5-9591) | kristina.weber@zoetis.com<mailto:shana.hull@zoetis.com>
Visit Us http://www.zoetis.com/

________________________________

**Comment by afrubin** [comment]
If all your reads start at the beginning of the variable region, then Enrich2 just needs the part of the wild type sequence that corresponds to the variable region.

If you shotgun-sequenced the population of variants, we can't resolve which reads derive from which variant molecule. This poses a problem for variant counting that is independent of the analysis method or program. If you want to discuss your experimental design and sequencing strategy in more detail, please email me directly at alan.rubin@wehi.edu.au
