### ISSUE TITLE
Counts tsv files on experiement level contain only NAs

### ISSUE THREAD

**Issue by hezscha** [FowlerLab/Enrich2#44]
Hi,
I noticed that on the experiment level the tsv count files contain only NA's, but the counts files at the selection levels and lower are fine. Is this a bug?

**Comment by afrubin** [comment]
Does this also happen if you run the example data (https://github.com/fowlerlab/enrich2-example)?

**Comment by hezscha** [comment]
Just checked, yes. It's not much of a problem since I can just get counts from the lower level tsv files, I just thought I'd mention it.

**Comment by rmenafra** [comment]
Hi I have the same problem, I was wondering if the issue was solved.

**Comment by afrubin** [comment]
> Hi I have the same problem, I was wondering if the issue was solved.

This may be addressed in a future version of the software, but for now I encourage you to use the above workaround and get the counts from the selection-level TSV files.

**Comment by rmenafra** [comment]
Is there any calculation applied to get the combined counts on the experiment level?

**Comment by afrubin** [comment]
> Is there any calculation applied to get the combined counts on the experiment level?

There's no calculation applied. The counts are the same from the seqlib level through to the selection and experiment. They're just organized in a single dataframe for convenience.

**Comment by rmenafra** [comment]
Clear, thanks!
