### ISSUE TITLE
Variants with different scores in main_variant_scores .tsv files

### ISSUE THREAD

**Issue by alexsupertramp3** [FowlerLab/Enrich2#47]
Apologies if this is explained elsewhere, but I have been unable to find a specific reference on here or the readthedocs page yet.

I am able to run the pipeline without issue, however in the output .tsv files for variants scores, I don't understand why some variants are separated onto multiple lines with different scores, despite the amino acid mutation being the same (below are a couple of examples). I am trying to create a file that contains a single entry for each amino acid variant, with a single corresponding score , however I am unsure how to condense the score of variants where there are multiple scores like this

Value	score		SE
c.4C>G (p.Gln2Val), c.5A>T (p.Gln2Val)	-0.094697918	0.066334765
c.4C>G (p.Gln2Val), c.5A>T (p.Gln2Val), c.6G>C (p.Gln2Val)	-0.056876483	0.033448828

value	score		SE
c.89T>C (p.Val30Ala), c.90T>A (p.Val30Ala)	-1.956064063	0.45982757
c.89T>C (p.Val30Ala), c.90T>C (p.Val30Ala)	-0.26482215	0.112174156
c.89T>C (p.Val30Ala), c.90T>G (p.Val30Ala)	-0.195519467	0.095803702

**Comment by afrubin** [comment]
Enrich2 scores variants both at the nucleotide level and at the amino acid level. There should be one set of output files for each of these cases.

Those are different variants at the nucleotide level, so they have separate scores. Some users find it useful to look at these as a sort of internal technical replication.

If you look at the amino acid level scores, you'll only see a single score for each amino acid change. Nucleotide variants with the same amino acid consequence are combined by summing the variant counts in each time point, which should be described in the documentation and/or the paper.

This isn't a bug so I'll go ahead and close this issue, but feel free to reply if you have followup questions!

**Comment by alexsupertramp3** [comment]
Yes I see what you are saying now, and I have identified the correct output file, thanks for getting back.
