### ISSUE TITLE
Standalone Sequence function Heatmap Plotting Script

### ISSUE THREAD

**Issue by alexsupertramp3** [FowlerLab/Enrich2#48]
I am a big fan of the heatmap plots this pipeline generates (and the pipeline in general) and I was wondering if there was an adapted version of the sfmap.py script in which you simply feed it an input file with the variant names, scores, and SE, rather than from what I can tell, variables generated earlier on in the pipeline. I would like to compare the Enrich2 heatmaps with the fitness scores from a couple of other DMS pipelines, however their differing plotting styles makes doing so less than optimal.

**Comment by afrubin** [comment]
Glad you like the plots! The sfmap.py script is hard to separate from the rest of the Enrich2 machinery, but this is something I'm hoping to work on in the near future.

**Comment by alexsupertramp3** [comment]
Okay thanks!
