### ISSUE TITLE
Run won't finish

### ISSUE THREAD

**Issue by AAdeniran** [FowlerLab/Enrich2#5]
Hello,

I am trying to run Enrich2 with the sample data set but receive the following error:

**TypeError: shape must be an integer or sequence: 8L**

I have attached the full log for reference. Do you have any suggestions on how to move forward?

Thanks,
[2017.1.20_Enrich2_log.txt](https://github.com/FowlerLab/Enrich2/files/720163/2017.1.20_Enrich2_log.txt)

Bola

**Comment by afrubin** [comment]
Thanks for the report. I haven't seen this error before. Could you please list your OS version and the version of the Enrich2 dependencies so I can try to reproduce it?

**Comment by AAdeniran** [comment]
Thanks. I am using Windows 10 and the following package versions:

NumPy

1.11.3

SciPy

0.18.1

Pandas

0.19.2

PyTables

3.3.0

Statsmodels

0.6.1

matplotlib

1.4.3

**Comment by AAdeniran** [comment]
Never mind- I reverted the dependencies to old versions and everything is working now. Thank you for getting back to me, though!

**Comment by afrubin** [comment]
Thanks again for posting. Glad you got it working! I'll make sure this isn't an issue in Enrich2 with the the listed dependency versions.
