### ISSUE TITLE
H5. file filled with N/A

### ISSUE THREAD

**Issue by diabatem1** [FowlerLab/Enrich2#51]
I was successfully able to run a json on enrich2. When I tried to use the generated .h5 file for the experiment the all of the counts are reported as NA, despite there being calculated scores. When I examined the generated .tsv files for each of the replicates, there are counts generated. Is there a reason why the counts are not being reported in the master .h5 file? Or is there a [workaround]([CC3_barcodes_reverse_exp.h5.zip](https://github.com/FowlerLab/Enrich2/files/7522635/CC3_barcodes_reverse_exp.h5.zip)) to import the counts from the .tsv files into the master .h5 file. Below I've attached the .h5 file

**Comment by afrubin** [comment]
Thanks for your report. This is a known bug. The counts are in the other .h5 files, so you can retrieve them from there, or read the .tsv files.
