### ISSUE TITLE
Ignoring reference offset for protein changes (not a multiple of three)

### ISSUE THREAD

**Issue by ijhoskins** [FowlerLab/Enrich2#54]
```
2021-12-09 01:30:40,801 [enrich2.main] Detected a OverlapSeqLib config file
2021-12-09 01:30:40,801 [enrich2.wildtype.<class 'enrich2.wildtype.WildTypeSequence'>] Ignoring reference offset for protein changes (not a multiple of three)
```

Reading the documentation for Variant Parameters (https://enrich2.readthedocs.io/en/latest/seqlib_config.html), it says the reference offset is added to the variant position, but makes no mention that the offset must be a multiple of three. Is it assumed that the reference must only be a coding sequence? In my use case, I'd like to add an offset relative to a transcript start, not a CDS start. Either way, it would be helpful if this was explicit in the docs.

**Comment by afrubin** [comment]
Thanks, we'll make sure this is clarified (and supported) in future software.
