### ISSUE TITLE
Issue opening GUI

### ISSUE THREAD

**Issue by eaconley** [FowlerLab/Enrich2#57]
I recently downloaded and installed Enrich2 and its dependencies. I am trying to explore its functions using the example dataset. When I type 

enrich_gui

from the example directory in a terminal window, I ultimately get the error: 

  File "/Users/eaconley2/opt/anaconda3/lib/python3.9/site-packages/Enrich2-1.3.1-py3.9.egg/enrich2/fqread.py", line 29, in <module>
AttributeError: module 'string' has no attribute 'maketrans'

Attached is the full run from terminal window in case that is helpful.

Thanks!

<img width="957" alt="Screen Shot 2022-03-21 at 1 26 57 PM" src="https://user-images.githubusercontent.com/102071275/159339696-dde67e9e-ab30-4ef3-b423-a45f148160c0.png">

**Comment by BournSupremacy** [comment]
Hey @eaconley! I'm having the same problem as you did here and I guess it's to do with my Python version - I'm on an M1 Mac so struggling to get Python 2.7 running. Did you manage to fix this? Would you maybe be able to let me know how?
