### ISSUE TITLE
SeqLib not being add to the GUI

### ISSUE THREAD

**Issue by amirTaslim** [FowlerLab/Enrich2#62]
Hello,

I wanted to share that two years ago, I effectively utilized Enrich-2 to analyze my data. However, I am currently facing an issue where I am unable to incorporate any type of SeqLib data. Upon adding the SeqLib reads, nothing appears on the graphical user interface (GUI).

Would anyone be able to provide assistance or insight into resolving this matter?

Thank you in advance.

**Comment by afrubin** [comment]
I'm not sure how to resolve this. Are you unable to create any SeqLib objects in the GUI or is something else going on? Enrich2 is not being actively maintained, but I can try to help out if you want to provide additional information like some screenshots.
