### ISSUE TITLE
why use z-test when replicates are <30

### ISSUE THREAD

**Issue by yinshiyi** [FowlerLab/Enrich2#64]
Hi Developer,
I read through the [paper ](https://genomebiology.biomedcentral.com/articles/10.1186/s13059-017-1272-5).

> Enrich2 calculates raw p values for each score under the null hypothesis that the variant’s score is indistinguishable from wild-type using a z-test

And wondering when sample size is <30 most of the time for biological replicates, I think t-test could be used instead?

Many thanks.

**Comment by afrubin** [comment]
We use a z-test since we know the standard deviation for the variant score.
