### ISSUE TITLE
Poisson or Negative Binomial

### ISSUE THREAD

**Issue by yinshiyi** [FowlerLab/Enrich2#65]
Hi Developer,

In the [Enrich2 paper](https://genomebiology.biomedcentral.com/articles/10.1186/s13059-017-1272-5), Poisson assumption is implemented, similarly in the [DiMSum](https://genomebiology.biomedcentral.com/articles/10.1186/s13059-020-02091-3).

I would like to ask if other count distribution was considered, e.g. Negative Binomial like DeSeq2 for RNAseq? 
How would one choose Poisson or Negative Binomial? I read that Negative Binomial allows mean and variance to differ. Not sure how to empirically test which assumption makes sense in my DMS.

Many thanks.

**Comment by afrubin** [comment]
We opted for the simplest option (Poisson), but there are DMS papers that use DeSeq2's statistical methods for their analysis. I'm not sure how to tell which is better aside from using both methods and comparing the results.
